# fly.toml app configuration file generated for consulting-three-js on 2024-12-17T14:47:34Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'consulting-three-js'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
